services:
  # nginx
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8400:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/log:/var/log/nginx
      - ./dist:/var/www/html

volumes:
  socket:
